### ISSUE TITLE
CMAKE building SFML

### ISSUE THREAD

**Issue by CristianD1** [c29reid/Dolphin-Matchmaking-Server#11]
we need to build sfml before the cmake links everything

Options: 
1. brew install sfml (for osx)
2. Find method to get cmake to build and then link???? (kill me pls, but probably the best)

option 1: the below line would have to reference a file in the users filesystem
see: 
https://github.com/c29reid/Dolphin-Matchmaking-Server/blob/master/CMakeLists.txt#L19

**Comment by c29reid** [comment]
#2 gl

**Comment by CristianD1** [comment]
make looks fine.

need to get make to build with c++14

**Comment by c29reid** [comment]
Cmake + SFML works fine now right?

**Comment by CristianD1** [comment]
👍
