### ISSUE TITLE
Make an output class

### ISSUE THREAD

**Issue by c29reid** [c29reid/Dolphin-Matchmaking-Server#5]
This class will be used to print what the server is doing to the console.
It should be able to be used concurrently without mangling output together.
It should also preferably block the connection thread as little as possible, this may require caching output strings.

**Comment by c29reid** [comment]
I would suggest looking in to this cristian

**Comment by CristianD1** [comment]
Essentially a queue of messages to be read using a sender id and display according to said id?

**Comment by CristianD1** [comment]
time stamp
replace couts we use

**Comment by CristianD1** [comment]
k
