### ISSUE TITLE
Support for a server side config

### ISSUE THREAD

**Issue by c29reid** [c29reid/Dolphin-Matchmaking-Server#9]
The server should have a config for things like the port, the time to allow clients to pile in the queue and other potentially useful options.

These config values should be propagated to some class (global maybe?) to be easily accessed.

**Comment by CristianD1** [comment]
Forgot what fixes you wanted for this. remind me?

**Comment by c29reid** [comment]
Actually use instances and make the object read the file itself when instantiated

**Comment by CristianD1** [comment]
avitally

**Comment by c29reid** [comment]
?

**Comment by CristianD1** [comment]
Done
https://github.com/c29reid/Dolphin-Matchmaking-Server/blob/master/source/Config.h
